name: CI
on:
  - push

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ["1.9", "1.10", "1.11", "1.12"]
    steps:
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: x64
      - name: instantiate environment
        run: |
            pwd
            julia --project=lr -e '
              using Pkg
              Pkg.add("BenchmarkTools")
              Pkg.add("ArgParse")
              Pkg.add("HDF5")
              Pkg.add("Test")
              Pkg.add(url="https://github.com/JuliaStellarDynamics/OrbitalElements.jl.git")
              Pkg.add(url="https://github.com/JuliaStellarDynamics/DistributionFunctions.jl.git")
              Pkg.add(url="https://github.com/JuliaStellarDynamics/FiniteHilbertTransform.jl.git")
              Pkg.add(url="https://github.com/JuliaStellarDynamics/AstroBasis.jl.git")
              Pkg.add(url="https://github.com/JuliaStellarDynamics/LinearResponse.jl.git", rev="v0.11.0")'
            ls
            julia --project=lr -e '
              using Pkg
              Pkg.develop(PackageSpec(path="/home/runner/work/LinearResponse.jl/LinearResponse.jl/lr"))'
            julia --threads=1 --project=lr test/runtests.jl


