name: Unit Test
on:
  - push

jobs:
  Benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.9
          arch: x64
      - name: instantiate environment
        run: |
            pwd
            julia --project=lr -e '
              using Pkg
              Pkg.add("BenchmarkTools")
              Pkg.add("ArgParse")
              Pkg.add("HDF5")
              Pkg.add("Test")
              Pkg.add(url="https://github.com/JuliaStellarDynamics/OrbitalElements.jl.git")
              Pkg.add(url="https://github.com/JuliaStellarDynamics/FiniteHilbertTransform.jl.git")
              Pkg.add(url="https://github.com/JuliaStellarDynamics/AstroBasis.jl.git")
              Pkg.add(url="https://github.com/JuliaStellarDynamics/LinearResponse.jl.git")'
            ls
            julia --project=lr -e '
              using Pkg
              Pkg.develop(PackageSpec(path="/home/runner/work/LinearResponse.jl/LinearResponse.jl"))'
            julia --project=lr test/runtests.jl
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info

